quarkus.liquibase.migrate-at-start=true
quarkus.liquibase.change-log=db/changeLog.yaml

quarkus.transaction-manager.default-transaction-timeout=PT5M
quarkus.http.test-timeout=PT5M
quarkus.http.read-timeout=PT5M

mock.user.id=1
mock.transaction.id=4711
